language: java
skip_cleanup: true
install:
- true
script:
- gradle buildAll
deploy:
  provider: releases
  api_key:
    secure: D2PatG1QBaH9EW4b58KKRa5JRhGVR7LuBrZBMMGJGroRSDYVNaCjmiTS1O+tmqn2h63nT9nkwJ0S4BavDo6u8eedZGjQVFcBWUQA+CkzPyk5tjD5ABnyXCzRNWquc5qLyd/FLRpDAKf9BoPeuSPiVFHxa+7dQVp36bWk+aO1KpC/WkSO9zL97rnbmE/mgNlI0vTyjyypw0eMs2gjNrTlZGMO3WcKAb63TwCCyNS5WIXEXhoP420SfDCHf6Nj9QQiENBzUtOe2HhvI8SUtQbM5j+4jIxMfwM4G8Q4Trf+WK3kvaIbj3mxlGjnOYFUl9xnPf805IPdI1fOBCmX0/9Fn3ut6kGbkM/K5pfexHbmelgzLnvD3aEv1IkLh+5Rkq9gdMtZCNq0F9jCacNWId/gqe27pKdGoM7Zks5Y+NoW24krl5KugRNAUidvDYmsd6jvudLu385adBNBafRLS3/gSKFiBVKYeZj2Y0kWkK+j6UBfpJbx3Ez4rCH5jfncATAHnlO1iS6k4mOlxqd4ZQR9mQngXtCEDY45OZI9wttz2RXpPhIm3ZdX2ktPs+nOE8gyApiGfujPLbluqhz8CgBHxH5FUsF2o+Y9K7jin7itLjSKg97m6+txmtS/uIOkv+5Bg3milLwr+AMzyPenw3zsZ5FVNVWsPcogB40aOls3WNI=
  file_glob: true
  file:
  - build/Hypovolemia_*_Client.zip
  - build/Hypovolemia_*_Server.zip
  on:
    tags: true